const AppointmentList = [
  {
    id: 1,
    doctorName: "Dr. Tanzina Ahmed",
    patientName: "Rahim Ahmed",
    appointmentName: "General Health Consultation",
    isVisible: true,
  },
  {
    id: 2,
    doctorName: "Dr. Mehedi Hasan",
    patientName: "Karim Hasan",
    appointmentName: "Child Fever Consultation",
    isVisible: true,
  },
  {
    id: 3,
    doctorName: "Dr. Raihan Ahmad",
    patientName: "Nusrat Jahan",
    appointmentName: "Internal Medicine Checkup",
    isVisible: true,
  },
  {
    id: 4,
    doctorName: "Dr. Mamunur Rashid",
    patientName: "Sadia Islam",
    appointmentName: "Back Pain Consultation",
    isVisible: true,
  },
  {
    id: 5,
    doctorName: "Dr. Sawrav Deb Bappy",
    patientName: "Tanvir Hossain",
    appointmentName: "Skin Allergy Consultation",
    isVisible: true,
  },
  {
    id: 6,
    doctorName: "Dr. Nabila Rahman",
    patientName: "Ayesha Karim",
    appointmentName: "Pregnancy Care Consultation",
    isVisible: true,
  },
  {
    id: 7,
    doctorName: "Dr. Farhana Islam",
    patientName: "Mehedi Hasan",
    appointmentName: "Heart Checkup",
    isVisible: true,
  },
  {
    id: 8,
    doctorName: "Dr. Tanvir Hossain",
    patientName: "Farhana Akter",
    appointmentName: "Migraine Consultation",
    isVisible: true,
  },
  {
    id: 9,
    doctorName: "Dr. Ayesha Karim",
    patientName: "Rafiq Uddin",
    appointmentName: "Dental Pain Consultation",
    isVisible: true,
  },
  {
    id: 10,
    doctorName: "Dr. Shakil Mahmud",
    patientName: "Samira Chowdhury",
    appointmentName: "Diabetes Consultation",
    isVisible: true,
  },
  {
    id: 11,
    doctorName: "Dr. Rafiq Hasan",
    patientName: "Arif Hossain",
    appointmentName: "Eye Problem Consultation",
    isVisible: true,
  },
  {
    id: 12,
    doctorName: "Dr. Samira Chowdhury",
    patientName: "Maliha Sultana",
    appointmentName: "Cancer Screening Advice",
    isVisible: true,
  },
  {
    id: 13,
    doctorName: "Dr. Arif Hossain",
    patientName: "Imran Kabir",
    appointmentName: "Family Medicine Consultation",
    isVisible: true,
  },
  {
    id: 14,
    doctorName: "Dr. Mahbuba Akter",
    patientName: "Jannatul Ferdous",
    appointmentName: "Rehabilitation Consultation",
    isVisible: true,
  },
  {
    id: 15,
    doctorName: "Dr. Nasir Uddin",
    patientName: "Tarek Aziz",
    appointmentName: "Fever Consultation",
    isVisible: true,
  },
  {
    id: 16,
    doctorName: "Dr. Maliha Sultana",
    patientName: "Lubna Yasmin",
    appointmentName: "Wellness Consultation",
    isVisible: true,
  },
  {
    id: 17,
    doctorName: "Dr. Imran Kabir",
    patientName: "Kamrul Islam",
    appointmentName: "Chest Medicine Consultation",
    isVisible: true,
  },
  {
    id: 18,
    doctorName: "Dr. Jannatul Ferdous",
    patientName: "Sadia Noor",
    appointmentName: "Kidney Health Consultation",
    isVisible: true,
  },
  {
    id: 19,
    doctorName: "Dr. Tarek Aziz",
    patientName: "Abdullah Al Mamun",
    appointmentName: "Cold and Allergy Consultation",
    isVisible: true,
  },
  {
    id: 20,
    doctorName: "Dr. Lubna Yasmin",
    patientName: "Nusrat Akter",
    appointmentName: "Joint Pain Consultation",
    isVisible: true,
  },
  {
    id: 21,
    doctorName: "Dr. Kamrul Islam",
    patientName: "Foysal Ahmed",
    appointmentName: "Gastric Problem Consultation",
    isVisible: true,
  },
  {
    id: 22,
    doctorName: "Dr. Sadia Noor",
    patientName: "Ruma Akter",
    appointmentName: "Lifestyle Guidance Consultation",
    isVisible: true,
  },
  {
    id: 23,
    doctorName: "Dr. Abdullah Al Mamun",
    patientName: "Saiful Islam",
    appointmentName: "Abdominal Pain Consultation",
    isVisible: true,
  },
  {
    id: 24,
    doctorName: "Dr. Nusrat Jahan",
    patientName: "Shirin Akhter",
    appointmentName: "Weakness and Anemia Consultation",
    isVisible: true,
  },
  {
    id: 25,
    doctorName: "Dr. Foysal Ahmed",
    patientName: "Parvez Rahman",
    appointmentName: "Neurology Consultation",
    isVisible: true,
  },
  {
    id: 26,
    doctorName: "Dr. Ruma Akter",
    patientName: "Tasnim Zaman",
    appointmentName: "Mental Wellness Consultation",
    isVisible: true,
  },
  {
    id: 27,
    doctorName: "Dr. Saiful Islam",
    patientName: "Hasan Mahmud",
    appointmentName: "Preventive Health Consultation",
    isVisible: true,
  },
  {
    id: 28,
    doctorName: "Dr. Shirin Akhter",
    patientName: "Mim Akter",
    appointmentName: "Newborn Care Consultation",
    isVisible: true,
  },
  {
    id: 29,
    doctorName: "Dr. Parvez Rahman",
    patientName: "Shakib Rahman",
    appointmentName: "Cardiovascular Consultation",
    isVisible: true,
  },
  {
    id: 30,
    doctorName: "Dr. Tasnim Zaman",
    patientName: "Nabila Hossain",
    appointmentName: "Breast Health Consultation",
    isVisible: true,
  },
];

export default AppointmentList;