const Doctors = [
  {
    id: 1,
    name: "Dr. Tanzina Ahmed",
    slug: "tanzina-ahmed",
    phone: "01710000001",
    requestStatus: "approved",
    isVisible: true,
    departmentSlug: "general-physician",
    departmentName: "General Physician",
    degree: "MBBS",
    speciality: "Gynae & Obs, General Physician",
    hospital: "Dhaka Medical College and Hospital",
    experience: 7,
    bmdcNumber: "94543",
    joinedDate: "5 Jul 2021",
    rating: 5,
    ratingCount: 971,
    fee: 320,
    followUpFee: 210,
    patientsAttended: 3200,
    doctorCode: "DT3076",
    gender: "female",
    status: "offline",
    image: "/Doctors/doctor1.jpg",
    about:
      "Dr. Tanzina Ahmed is an experienced general physician. She provides consultation for fever, flu, headache, infections, women health issues, and general medical problems.",
    availability: {
      instant: ["Sat - Wed (08:00 PM - 11:55 PM)", "Fri (11:00 AM - 01:00 PM)"],
      appointment: ["Sat - Fri (03:00 PM - 11:55 PM)"],
    },
  },

  {
    id: 2,
    name: "Dr. Mehedi Hasan",
    slug: "mehedi-hasan",
    phone: "01710000002",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "pediatrics",
    departmentName: "Pediatrics",
    degree: "MBBS, FCPS",
    speciality: "Pediatric Specialist",
    hospital: "Square Medical College Hospital",
    experience: 14,
    bmdcNumber: "88321",
    joinedDate: "12 Mar 2020",
    rating: 4.9,
    ratingCount: 400,
    fee: 700,
    followUpFee: 400,
    patientsAttended: 5100,
    doctorCode: "DT2081",
    gender: "male",
    status: "online",
    image: "/Doctors/doctor2.jpg",
    about:
      "Dr. Mehedi Hasan provides child health consultation, vaccination guidance, fever management, growth problems, and pediatric care.",
    availability: {
      instant: ["Sun - Thu (07:00 PM - 11:00 PM)"],
      appointment: ["Sat - Fri (04:00 PM - 10:00 PM)"],
    },
  },

  {
    id: 3,
    name: "Dr. Raihan Ahmad",
    slug: "raihan-ahmad",
    phone: "01710000003",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "internal-medicine",
    departmentName: "Internal Medicine",
    degree: "MBBS, MD",
    speciality: "Medicine Specialist",
    hospital: "National Institute of Neurosciences and Hospital",
    experience: 13,
    bmdcNumber: "72190",
    joinedDate: "8 Jan 2022",
    rating: 5,
    ratingCount: 758,
    fee: 1050,
    followUpFee: 600,
    patientsAttended: 4200,
    doctorCode: "DT4002",
    gender: "male",
    status: "online",
    image: "/Doctors/doctor3.jpg",
    about:
      "Dr. Raihan Ahmad treats adult health problems, diabetes, high blood pressure, infection, weakness, and complex internal medicine cases.",
    availability: {
      instant: ["Sat - Thu (06:00 PM - 10:30 PM)"],
      appointment: ["Sat - Fri (05:00 PM - 11:00 PM)"],
    },
  },

  {
    id: 4,
    name: "Dr. Mamunur Rashid",
    slug: "mamunur-rashid",
    phone: "01710000004",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "physical-medicine",
    departmentName: "Physical Medicine",
    degree: "MBBS, MS",
    speciality: "Physical Medicine Specialist",
    hospital: "Kurmitala General Hospital",
    experience: 15,
    bmdcNumber: "65412",
    joinedDate: "20 Sep 2019",
    rating: 5,
    ratingCount: 305,
    fee: 1000,
    followUpFee: 550,
    patientsAttended: 3900,
    doctorCode: "DT1124",
    gender: "male",
    status: "offline",
    image: "/Doctors/doctor4.jpg",
    about:
      "Dr. Mamunur Rashid provides treatment for bone, joint, muscle pain, back pain, rehabilitation, and physical recovery problems.",
    availability: {
      instant: ["Mon - Thu (08:00 PM - 10:00 PM)"],
      appointment: ["Sat - Thu (06:00 PM - 10:00 PM)"],
    },
  },

  {
    id: 5,
    name: "Dr. Sawrav Deb Bappy",
    slug: "sawrav-deb-bappy",
    phone: "01710000005",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "dermatology",
    departmentName: "Dermatology",
    degree: "MBBS, DDV",
    speciality: "Dermatologist",
    hospital: "Bangabandhu Sheikh Mujib Medical University",
    experience: 9,
    bmdcNumber: "77890",
    joinedDate: "18 Jun 2021",
    rating: 4.8,
    ratingCount: 280,
    fee: 750,
    followUpFee: 400,
    patientsAttended: 2600,
    doctorCode: "DT5067",
    gender: "male",
    status: "online",
    image: "/Doctors/doctor5.jpg",
    about:
      "Dr. Sawrav Deb Bappy treats acne, allergy, skin infection, hair fall, dandruff, eczema, and other skin-related problems.",
    availability: {
      instant: ["Sat - Wed (09:00 PM - 11:30 PM)"],
      appointment: ["Sat - Fri (04:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 6,
    name: "Dr. Nabila Rahman",
    slug: "nabila-rahman",
    phone: "01710000006",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "gyne-obs",
    departmentName: "Gyne & Obs",
    degree: "MBBS, FCPS",
    speciality: "Gynecologist",
    hospital: "Central Hospital Limited",
    experience: 11,
    bmdcNumber: "90123",
    joinedDate: "2 Feb 2020",
    rating: 4.9,
    ratingCount: 612,
    fee: 900,
    followUpFee: 500,
    patientsAttended: 4700,
    doctorCode: "DT6182",
    gender: "female",
    status: "online",
    image: "/Doctors/doctor6.jpg",
    about:
      "Dr. Nabila Rahman provides consultation for pregnancy care, menstrual problems, fertility issues, PCOS, and women health.",
    availability: {
      instant: ["Sun - Thu (07:30 PM - 11:00 PM)"],
      appointment: ["Sat - Fri (03:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 7,
    name: "Dr. Farhana Islam",
    slug: "farhana-islam",
    phone: "01710000007",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "cardiology",
    departmentName: "Cardiology",
    degree: "MBBS, MD Cardiology",
    speciality: "Cardiologist",
    hospital: "National Heart Foundation Hospital",
    experience: 12,
    bmdcNumber: "81234",
    joinedDate: "15 Aug 2020",
    rating: 4.9,
    ratingCount: 530,
    fee: 1200,
    followUpFee: 700,
    patientsAttended: 4300,
    doctorCode: "DT7190",
    gender: "female",
    status: "offline",
    image: "/Doctors/doctor7.jpg",
    about:
      "Dr. Farhana Islam treats chest pain, high blood pressure, heart disease, palpitation, and cardiac risk management.",
    availability: {
      instant: ["Mon - Wed (08:00 PM - 10:00 PM)"],
      appointment: ["Sat - Thu (05:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 8,
    name: "Dr. Tanvir Hossain",
    slug: "tanvir-hossain",
    phone: "01710000008",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "neurology",
    departmentName: "Neurology",
    degree: "MBBS, MD Neurology",
    speciality: "Neurologist",
    hospital: "National Institute of Neurosciences",
    experience: 10,
    bmdcNumber: "73456",
    joinedDate: "10 Oct 2021",
    rating: 4.8,
    ratingCount: 375,
    fee: 1100,
    followUpFee: 650,
    patientsAttended: 3500,
    doctorCode: "DT8304",
    gender: "male",
    status: "online",
    image: "/Doctors/doctor8.jpg",
    about:
      "Dr. Tanvir Hossain provides consultation for headache, migraine, stroke, nerve pain, epilepsy, and neurological disorders.",
    availability: {
      instant: ["Sat - Thu (09:00 PM - 11:30 PM)"],
      appointment: ["Sat - Fri (06:00 PM - 10:00 PM)"],
    },
  },

  {
    id: 9,
    name: "Dr. Ayesha Karim",
    slug: "ayesha-karim",
    phone: "01710000009",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "dentistry",
    departmentName: "Dentistry",
    degree: "BDS, FCPS",
    speciality: "Dental Surgeon",
    hospital: "Dhaka Dental College",
    experience: 8,
    bmdcNumber: "66781",
    joinedDate: "22 Nov 2022",
    rating: 4.7,
    ratingCount: 245,
    fee: 500,
    followUpFee: 300,
    patientsAttended: 2100,
    doctorCode: "DT9445",
    gender: "female",
    status: "online",
    image: "/Doctors/doctor9.jpg",
    about:
      "Dr. Ayesha Karim treats toothache, gum problems, dental infection, scaling, filling, and oral health issues.",
    availability: {
      instant: ["Sun - Thu (06:00 PM - 10:00 PM)"],
      appointment: ["Sat - Fri (04:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 10,
    name: "Dr. Shakil Mahmud",
    slug: "shakil-mahmud",
    phone: "01710000010",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "internal-medicine",
    departmentName: "Internal Medicine",
    degree: "MBBS, MD Endocrinology",
    speciality: "Diabetes and Hormone Specialist",
    hospital: "BIRDEM General Hospital",
    experience: 16,
    bmdcNumber: "55231",
    joinedDate: "9 Apr 2019",
    rating: 5,
    ratingCount: 690,
    fee: 1300,
    followUpFee: 750,
    patientsAttended: 6200,
    doctorCode: "DT1022",
    gender: "male",
    status: "offline",
    image: "/Doctors/doctor10.jpg",
    about:
      "Dr. Shakil Mahmud treats diabetes, thyroid disease, hormone imbalance, obesity, and internal medicine-related health problems.",
    availability: {
      instant: ["Tue - Thu (08:00 PM - 10:30 PM)"],
      appointment: ["Sat - Thu (05:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 11,
    name: "Dr. Rafiq Hasan",
    slug: "rafiq-hasan",
    phone: "01710000011",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "ophthalmology",
    departmentName: "Ophthalmology",
    degree: "MBBS, MS Eye",
    speciality: "Eye Specialist",
    hospital: "Ispahani Islamia Eye Institute",
    experience: 12,
    bmdcNumber: "61245",
    joinedDate: "5 May 2020",
    rating: 4.8,
    ratingCount: 390,
    fee: 800,
    followUpFee: 450,
    patientsAttended: 3000,
    doctorCode: "DT1108",
    gender: "male",
    status: "online",
    image: "/Doctors/doctor11.jpg",
    about:
      "Dr. Rafiq Hasan provides consultation for eye pain, vision problem, redness, infection, dry eye, and eye disease.",
    availability: {
      instant: ["Sat - Wed (07:00 PM - 10:00 PM)"],
      appointment: ["Sat - Fri (04:00 PM - 08:00 PM)"],
    },
  },

  {
    id: 12,
    name: "Dr. Samira Chowdhury",
    slug: "samira-chowdhury",
    phone: "01710000012",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "oncology",
    departmentName: "Oncology",
    degree: "MBBS, MD Oncology",
    speciality: "Cancer Specialist",
    hospital: "National Institute of Cancer Research",
    experience: 14,
    bmdcNumber: "71344",
    joinedDate: "14 Jan 2020",
    rating: 4.9,
    ratingCount: 418,
    fee: 1400,
    followUpFee: 800,
    patientsAttended: 3300,
    doctorCode: "DT1244",
    gender: "female",
    status: "offline",
    image: "/Doctors/doctor12.jpg",
    about:
      "Dr. Samira Chowdhury provides consultation for cancer diagnosis, treatment planning, chemotherapy advice, and follow-up care.",
    availability: {
      instant: ["Sun - Tue (08:00 PM - 10:00 PM)"],
      appointment: ["Sat - Thu (05:00 PM - 08:30 PM)"],
    },
  },

  {
    id: 13,
    name: "Dr. Arif Hossain",
    slug: "arif-hossain",
    phone: "01710000013",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "family-medicine",
    departmentName: "Family Medicine",
    degree: "MBBS, MPH",
    speciality: "Family Medicine Specialist",
    hospital: "Ibn Sina Medical College Hospital",
    experience: 9,
    bmdcNumber: "83219",
    joinedDate: "30 Jul 2021",
    rating: 4.7,
    ratingCount: 320,
    fee: 600,
    followUpFee: 350,
    patientsAttended: 2800,
    doctorCode: "DT1320",
    gender: "male",
    status: "online",
    image: "/Doctors/doctor13.jpg",
    about:
      "Dr. Arif Hossain provides family healthcare consultation for children, adults, elderly patients, and preventive health advice.",
    availability: {
      instant: ["Sat - Thu (05:00 PM - 11:00 PM)"],
      appointment: ["Sat - Fri (10:00 AM - 08:00 PM)"],
    },
  },

  {
    id: 14,
    name: "Dr. Mahbuba Akter",
    slug: "mahbuba-akter",
    phone: "01710000014",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "physical-medicine",
    departmentName: "Physical Medicine",
    degree: "MBBS, FCPS Physical Medicine",
    speciality: "Rehabilitation Specialist",
    hospital: "CRP Savar",
    experience: 10,
    bmdcNumber: "90218",
    joinedDate: "1 Dec 2020",
    rating: 4.8,
    ratingCount: 210,
    fee: 750,
    followUpFee: 400,
    patientsAttended: 1900,
    doctorCode: "DT1409",
    gender: "female",
    status: "online",
    image: "/Doctors/doctor14.jpg",
    about:
      "Dr. Mahbuba Akter treats back pain, stroke rehabilitation, movement difficulty, joint stiffness, and physical recovery problems.",
    availability: {
      instant: ["Mon - Thu (07:00 PM - 10:00 PM)"],
      appointment: ["Sat - Fri (04:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 15,
    name: "Dr. Nasir Uddin",
    slug: "nasir-uddin",
    phone: "01710000015",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "general-physician",
    departmentName: "General Physician",
    degree: "MBBS, MS",
    speciality: "General Physician",
    hospital: "Shaheed Suhrawardy Medical College Hospital",
    experience: 13,
    bmdcNumber: "71900",
    joinedDate: "18 Feb 2019",
    rating: 4.9,
    ratingCount: 360,
    fee: 1000,
    followUpFee: 600,
    patientsAttended: 3400,
    doctorCode: "DT1501",
    gender: "male",
    status: "offline",
    image: "/Doctors/doctor15.jpg",
    about:
      "Dr. Nasir Uddin provides consultation for fever, weakness, infection, urinary discomfort, and general health problems.",
    availability: {
      instant: ["Sat - Tue (08:00 PM - 10:30 PM)"],
      appointment: ["Sat - Thu (05:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 16,
    name: "Dr. Maliha Sultana",
    slug: "maliha-sultana",
    phone: "01710000016",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "family-medicine",
    departmentName: "Family Medicine",
    degree: "MBBS, MD",
    speciality: "Family Health Consultant",
    hospital: "National Institute of Mental Health",
    experience: 8,
    bmdcNumber: "64092",
    joinedDate: "7 Jul 2022",
    rating: 4.8,
    ratingCount: 275,
    fee: 900,
    followUpFee: 500,
    patientsAttended: 2300,
    doctorCode: "DT1608",
    gender: "female",
    status: "online",
    image: "/Doctors/doctor16.jpg",
    about:
      "Dr. Maliha Sultana provides consultation for stress-related physical issues, sleep problems, family health concerns, and wellness guidance.",
    availability: {
      instant: ["Sun - Thu (08:00 PM - 11:00 PM)"],
      appointment: ["Sat - Fri (05:00 PM - 10:00 PM)"],
    },
  },

  {
    id: 17,
    name: "Dr. Imran Kabir",
    slug: "imran-kabir",
    phone: "01710000017",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "internal-medicine",
    departmentName: "Internal Medicine",
    degree: "MBBS, MD Chest Medicine",
    speciality: "Medicine Specialist",
    hospital: "National Institute of Diseases of the Chest",
    experience: 11,
    bmdcNumber: "88770",
    joinedDate: "11 Jan 2021",
    rating: 4.7,
    ratingCount: 330,
    fee: 850,
    followUpFee: 500,
    patientsAttended: 3100,
    doctorCode: "DT1711",
    gender: "male",
    status: "online",
    image: "/Doctors/doctor17.jpg",
    about:
      "Dr. Imran Kabir treats cough, asthma, breathing difficulty, chest infection, COPD, fever, and internal medicine-related diseases.",
    availability: {
      instant: ["Sat - Thu (07:00 PM - 10:30 PM)"],
      appointment: ["Sat - Fri (04:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 18,
    name: "Dr. Jannatul Ferdous",
    slug: "jannatul-ferdous",
    phone: "01710000018",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "internal-medicine",
    departmentName: "Internal Medicine",
    degree: "MBBS, MD",
    speciality: "Medicine Specialist",
    hospital: "Kidney Foundation Hospital",
    experience: 12,
    bmdcNumber: "71231",
    joinedDate: "4 Apr 2020",
    rating: 4.8,
    ratingCount: 298,
    fee: 1000,
    followUpFee: 600,
    patientsAttended: 2700,
    doctorCode: "DT1804",
    gender: "female",
    status: "offline",
    image: "/Doctors/doctor18.jpg",
    about:
      "Dr. Jannatul Ferdous provides consultation for kidney-related symptoms, urine problems, high blood pressure, diabetes, and general internal medicine issues.",
    availability: {
      instant: ["Mon - Wed (08:00 PM - 10:00 PM)"],
      appointment: ["Sat - Thu (05:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 19,
    name: "Dr. Tarek Aziz",
    slug: "tarek-aziz",
    phone: "01710000019",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "general-physician",
    departmentName: "General Physician",
    degree: "MBBS, MS",
    speciality: "General Physician",
    hospital: "Dhaka Medical College Hospital",
    experience: 10,
    bmdcNumber: "55678",
    joinedDate: "19 May 2021",
    rating: 4.7,
    ratingCount: 245,
    fee: 700,
    followUpFee: 400,
    patientsAttended: 2500,
    doctorCode: "DT1905",
    gender: "male",
    status: "online",
    image: "/Doctors/doctor19.jpg",
    about:
      "Dr. Tarek Aziz treats fever, cold, allergy, throat discomfort, headache, sinus symptoms, and general health conditions.",
    availability: {
      instant: ["Sat - Thu (06:00 PM - 10:00 PM)"],
      appointment: ["Sat - Fri (03:00 PM - 08:00 PM)"],
    },
  },

  {
    id: 20,
    name: "Dr. Lubna Yasmin",
    slug: "lubna-yasmin",
    phone: "01710000020",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "physical-medicine",
    departmentName: "Physical Medicine",
    degree: "MBBS, MD",
    speciality: "Pain and Rehabilitation Specialist",
    hospital: "BSMMU",
    experience: 9,
    bmdcNumber: "99012",
    joinedDate: "23 Aug 2021",
    rating: 4.8,
    ratingCount: 225,
    fee: 950,
    followUpFee: 550,
    patientsAttended: 2200,
    doctorCode: "DT2017",
    gender: "female",
    status: "online",
    image: "/Doctors/doctor20.jpg",
    about:
      "Dr. Lubna Yasmin treats arthritis, joint pain, body pain, muscle stiffness, movement limitation, and rehabilitation-related problems.",
    availability: {
      instant: ["Sun - Thu (08:00 PM - 10:30 PM)"],
      appointment: ["Sat - Thu (05:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 21,
    name: "Dr. Kamrul Islam",
    slug: "kamrul-islam",
    phone: "01710000021",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "internal-medicine",
    departmentName: "Internal Medicine",
    degree: "MBBS, MD",
    speciality: "Medicine Specialist",
    hospital: "Popular Medical College Hospital",
    experience: 15,
    bmdcNumber: "78901",
    joinedDate: "3 Mar 2019",
    rating: 4.9,
    ratingCount: 480,
    fee: 1200,
    followUpFee: 700,
    patientsAttended: 4600,
    doctorCode: "DT2103",
    gender: "male",
    status: "offline",
    image: "/Doctors/doctor21.jpg",
    about:
      "Dr. Kamrul Islam provides consultation for gastric problems, liver symptoms, abdominal pain, acidity, diabetes, and internal medicine conditions.",
    availability: {
      instant: ["Tue - Thu (08:00 PM - 10:00 PM)"],
      appointment: ["Sat - Thu (05:00 PM - 09:00 PM)"],
    },
  },

  {
    id: 22,
    name: "Dr. Sadia Noor",
    slug: "sadia-noor",
    phone: "01710000022",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "family-medicine",
    departmentName: "Family Medicine",
    degree: "MBBS, MPH",
    speciality: "Family Health Advisor",
    hospital: "MediGo Family Health Center",
    experience: 6,
    bmdcNumber: "N/A",
    joinedDate: "11 Sep 2022",
    rating: 4.7,
    ratingCount: 180,
    fee: 500,
    followUpFee: 300,
    patientsAttended: 1500,
    doctorCode: "DT2206",
    gender: "female",
    status: "online",
    image: "/Doctors/doctor22.jpg",
    about:
      "Dr. Sadia Noor provides family health advice, preventive health support, lifestyle guidance, nutrition discussion, and wellness consultation.",
    availability: {
      instant: ["Sat - Thu (05:00 PM - 09:00 PM)"],
      appointment: ["Sat - Fri (10:00 AM - 08:00 PM)"],
    },
  },

  {
    id: 23,
    name: "Dr. Abdullah Al Mamun",
    slug: "abdullah-al-mamun",
    phone: "01710000023",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "internal-medicine",
    departmentName: "Internal Medicine",
    degree: "MBBS, FCPS",
    speciality: "Medicine and Surgery Consultant",
    hospital: "Chittagong Medical College Hospital",
    experience: 17,
    bmdcNumber: "62345",
    joinedDate: "21 Feb 2018",
    rating: 4.9,
    ratingCount: 510,
    fee: 1300,
    followUpFee: 800,
    patientsAttended: 5000,
    doctorCode: "DT2317",
    gender: "male",
    status: "offline",
    image: "/Doctors/doctor23.jpg",
    about:
      "Dr. Abdullah Al Mamun provides consultation for abdominal pain, digestive symptoms, infection, weakness, and adult health problems.",
    availability: {
      instant: ["Sat - Mon (08:00 PM - 10:00 PM)"],
      appointment: ["Sat - Thu (04:00 PM - 08:00 PM)"],
    },
  },

  {
    id: 24,
    name: "Dr. Nusrat Jahan",
    slug: "nusrat-jahan",
    phone: "01710000024",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "internal-medicine",
    departmentName: "Internal Medicine",
    degree: "MBBS, MD",
    speciality: "Medicine Specialist",
    hospital: "Dhaka Medical College Hospital",
    experience: 10,
    bmdcNumber: "77112",
    joinedDate: "6 Jun 2020",
    rating: 4.8,
    ratingCount: 260,
    fee: 1000,
    followUpFee: 600,
    patientsAttended: 2400,
    doctorCode: "DT2410",
    gender: "female",
    status: "online",
    image: "/Doctors/doctor24.jpg",
    about:
      "Dr. Nusrat Jahan treats anemia symptoms, weakness, blood-related concerns, fever, infection, and general internal medicine conditions.",
    availability: {
      instant: ["Sun - Thu (07:30 PM - 10:30 PM)"],
      appointment: ["Sat - Fri (04:00 PM - 08:00 PM)"],
    },
  },

  {
    id: 25,
    name: "Dr. Foysal Ahmed",
    slug: "foysal-ahmed",
    phone: "01710000025",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "neurology",
    departmentName: "Neurology",
    degree: "MBBS, MS Neurosurgery",
    speciality: "Neurology Consultant",
    hospital: "National Institute of Neurosciences",
    experience: 18,
    bmdcNumber: "69090",
    joinedDate: "13 Dec 2017",
    rating: 4.9,
    ratingCount: 335,
    fee: 1500,
    followUpFee: 900,
    patientsAttended: 4100,
    doctorCode: "DT2518",
    gender: "male",
    status: "offline",
    image: "/Doctors/doctor25.jpg",
    about:
      "Dr. Foysal Ahmed provides consultation for brain, nerve, spine, headache, neurological symptoms, and neurosurgical advice.",
    availability: {
      instant: ["Mon - Wed (09:00 PM - 10:30 PM)"],
      appointment: ["Sat - Thu (05:00 PM - 08:00 PM)"],
    },
  },

  {
    id: 26,
    name: "Dr. Ruma Akter",
    slug: "ruma-akter",
    phone: "01710000026",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "family-medicine",
    departmentName: "Family Medicine",
    degree: "MBBS, MSc Clinical Psychology",
    speciality: "Family Wellness Consultant",
    hospital: "MediGo Mental Health Center",
    experience: 7,
    bmdcNumber: "N/A",
    joinedDate: "24 Jan 2022",
    rating: 4.8,
    ratingCount: 190,
    fee: 650,
    followUpFee: 400,
    patientsAttended: 1800,
    doctorCode: "DT2607",
    gender: "female",
    status: "online",
    image: "/Doctors/doctor26.jpg",
    about:
      "Dr. Ruma Akter provides family wellness guidance, stress support, emotional health consultation, and lifestyle advice.",
    availability: {
      instant: ["Sat - Thu (06:00 PM - 11:00 PM)"],
      appointment: ["Sat - Fri (10:00 AM - 08:00 PM)"],
    },
  },

  {
    id: 27,
    name: "Dr. Saiful Islam",
    slug: "saiful-islam",
    phone: "01710000027",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "family-medicine",
    departmentName: "Family Medicine",
    degree: "MBBS, MPH",
    speciality: "Family Medicine Specialist",
    hospital: "MediGo Public Health Unit",
    experience: 9,
    bmdcNumber: "85210",
    joinedDate: "30 Oct 2021",
    rating: 4.6,
    ratingCount: 140,
    fee: 500,
    followUpFee: 250,
    patientsAttended: 1300,
    doctorCode: "DT2709",
    gender: "male",
    status: "online",
    image: "/Doctors/doctor27.jpg",
    about:
      "Dr. Saiful Islam provides family healthcare, preventive care, vaccination guidance, community health, and lifestyle advice.",
    availability: {
      instant: ["Sun - Thu (05:00 PM - 09:00 PM)"],
      appointment: ["Sat - Fri (09:00 AM - 06:00 PM)"],
    },
  },

  {
    id: 28,
    name: "Dr. Shirin Akhter",
    slug: "shirin-akhter",
    phone: "01710000028",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "pediatrics",
    departmentName: "Pediatrics",
    degree: "MBBS, MD Neonatology",
    speciality: "Newborn and Child Specialist",
    hospital: "Bangladesh Shishu Hospital",
    experience: 11,
    bmdcNumber: "77881",
    joinedDate: "16 May 2020",
    rating: 4.9,
    ratingCount: 315,
    fee: 950,
    followUpFee: 550,
    patientsAttended: 2900,
    doctorCode: "DT2811",
    gender: "female",
    status: "offline",
    image: "/Doctors/doctor28.jpg",
    about:
      "Dr. Shirin Akhter provides consultation for newborn care, premature baby care, feeding issues, neonatal infection, and child growth monitoring.",
    availability: {
      instant: ["Sat - Wed (08:00 PM - 10:30 PM)"],
      appointment: ["Sat - Thu (04:00 PM - 08:00 PM)"],
    },
  },

  {
    id: 29,
    name: "Dr. Parvez Rahman",
    slug: "parvez-rahman",
    phone: "01710000029",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "cardiology",
    departmentName: "Cardiology",
    degree: "MBBS, MS Vascular Surgery",
    speciality: "Cardiovascular Consultant",
    hospital: "National Institute of Cardiovascular Diseases",
    experience: 16,
    bmdcNumber: "60017",
    joinedDate: "5 Feb 2018",
    rating: 4.8,
    ratingCount: 220,
    fee: 1400,
    followUpFee: 800,
    patientsAttended: 2600,
    doctorCode: "DT2916",
    gender: "male",
    status: "offline",
    image: "/Doctors/doctor29.jpg",
    about:
      "Dr. Parvez Rahman provides consultation for blood vessel disease, leg swelling, circulation problems, blood pressure, and cardiovascular symptoms.",
    availability: {
      instant: ["Mon - Thu (08:00 PM - 10:00 PM)"],
      appointment: ["Sat - Thu (05:00 PM - 08:00 PM)"],
    },
  },

  {
    id: 30,
    name: "Dr. Tasnim Zaman",
    slug: "tasnim-zaman",
    phone: "01710000030",
    requestStatus: "pending",
    isVisible: true,
    departmentSlug: "oncology",
    departmentName: "Oncology",
    degree: "MBBS, FCPS Surgery",
    speciality: "Oncology and Breast Health Consultant",
    hospital: "United Hospital Limited",
    experience: 12,
    bmdcNumber: "89123",
    joinedDate: "28 Jun 2020",
    rating: 4.9,
    ratingCount: 295,
    fee: 1200,
    followUpFee: 700,
    patientsAttended: 2300,
    doctorCode: "DT3012",
    gender: "female",
    status: "online",
    image: "/Doctors/doctor30.jpg",
    about:
      "Dr. Tasnim Zaman provides consultation for breast lump, breast pain, cancer screening, oncology advice, and women breast health.",
    availability: {
      instant: ["Sun - Thu (07:00 PM - 10:00 PM)"],
      appointment: ["Sat - Fri (04:00 PM - 08:00 PM)"],
    },
  },
];

export default Doctors;